version: "3.8"
services:
  hosting-api:
    image: hosting-api
    container_name: hosting-api-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=hosting-api.salt-mine.io
      - LETSENCRYPT_HOST=hosting-api.salt-mine.io
      - LETSENCRYPT_EMAIL=olive@salt-mine.io
    network_mode: "webproxy"
    restart: always
